/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Point;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author razmi
 */
public class DaftarKucing extends javax.swing.JFrame {
    SetterGetter setget = new SetterGetter();
    DetailsTabel detail = new DetailsTabel();
    

    /**
     * Creates new form contohJFrame
     */
    public DaftarKucing() {
        initComponents();
        setLocationRelativeTo(null);
        Siamese.setSelected(true);
        sehari.setActionCommand("Sehari");
        lebihsehari.setActionCommand("Lebih Dari 1 Hari");
        Siamese.setActionCommand("Siamese");
        Persians.setActionCommand("Persians");
        Ragdoll.setActionCommand("Ragdoll");
        Britishshorthair.setActionCommand("British short hair");
        Anggora.setActionCommand("Anggora");
        Sphynxes.setActionCommand("Sphynxes");
        Domestik.setActionCommand("Domestik");
        Bengals.setActionCommand("Bengals");
    }
    
    void Berat (String berat1, String berat2, String berat3, String berat4, String berat5){
        ArrayList<String> berats = new ArrayList<>();
        Iterator<String> iter;
        berats.add("Pilih...");
        berats.add(berat1);
        berats.add(berat2);
        berats.add(berat3);
        berats.add(berat4);
        berats.add(berat5);
    }
        void Jam (String jam1, String jam2, String jam3, String jam4){
        ArrayList<String> jams = new ArrayList<>();
        Iterator<String> iter;
        jams.add("Pilih...");
        jams.add(jam1);
        jams.add(jam2);
        jams.add(jam3);
        jams.add(jam4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lamapenitipan = new javax.swing.ButtonGroup();
        jeniskucing = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftar = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Siamese = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        Persians = new javax.swing.JRadioButton();
        Ragdoll = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        Britishshorthair = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Anggora = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Sphynxes = new javax.swing.JRadioButton();
        Domestik = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        Bengals = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tanggal1 = new org.netbeans.modules.form.InvalidComponent();
        jLabel5 = new javax.swing.JLabel();
        tanggal2 = new org.netbeans.modules.form.InvalidComponent();
        namapemilik = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jam = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        sehari = new javax.swing.JRadioButton();
        lebihsehari = new javax.swing.JRadioButton();
        berat = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kucingan = new javax.swing.JButton();
        add = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        target = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daftar.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        daftar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Pemilik", "Jenis ", "Berat", "Lama ", "Tgl Masuk", "Tgl Diambil", "Jam "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(daftar);
        if (daftar.getColumnModel().getColumnCount() > 0) {
            daftar.getColumnModel().getColumn(0).setResizable(false);
            daftar.getColumnModel().getColumn(1).setResizable(false);
            daftar.getColumnModel().getColumn(2).setResizable(false);
            daftar.getColumnModel().getColumn(3).setResizable(false);
            daftar.getColumnModel().getColumn(4).setResizable(false);
            daftar.getColumnModel().getColumn(5).setResizable(false);
            daftar.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 58, 550, 541));

        jScrollPane3.setBackground(new java.awt.Color(102, 255, 51));
        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel4.setBackground(new java.awt.Color(159,217,245));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/siamese_jpg.jpg"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jeniskucing.add(Siamese);
        Siamese.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        Siamese.setText("Siamese");
        Siamese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiameseActionPerformed(evt);
            }
        });
        jPanel4.add(Siamese, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/persian_jpg.jpg"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jeniskucing.add(Persians);
        Persians.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        Persians.setText("Persians");
        Persians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersiansActionPerformed(evt);
            }
        });
        jPanel4.add(Persians, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 100, -1));

        jeniskucing.add(Ragdoll);
        Ragdoll.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        Ragdoll.setText("Ragdoll");
        Ragdoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RagdollActionPerformed(evt);
            }
        });
        jPanel4.add(Ragdoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/ragdoll_jpg.jpg"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jeniskucing.add(Britishshorthair);
        Britishshorthair.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        Britishshorthair.setText("British shorthair");
        Britishshorthair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BritishshorthairActionPerformed(evt);
            }
        });
        jPanel4.add(Britishshorthair, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 140, 160, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/british_jpg.jpg"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/anggora_jpg.jpg"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jeniskucing.add(Anggora);
        Anggora.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        Anggora.setText("Anggora");
        Anggora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnggoraActionPerformed(evt);
            }
        });
        jPanel4.add(Anggora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 100, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 710, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/sphynx_jpg.jpg"))); // NOI18N
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jeniskucing.add(Sphynxes);
        Sphynxes.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        Sphynxes.setText("Sphynxes");
        Sphynxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SphynxesActionPerformed(evt);
            }
        });
        jPanel4.add(Sphynxes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 110, -1));

        jeniskucing.add(Domestik);
        Domestik.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        Domestik.setText("Domestik");
        Domestik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DomestikActionPerformed(evt);
            }
        });
        jPanel4.add(Domestik, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 670, 110, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/kampung_jpg.jpg"))); // NOI18N
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        jeniskucing.add(Bengals);
        Bengals.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        Bengals.setText("Bengals");
        Bengals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BengalsActionPerformed(evt);
            }
        });
        jPanel4.add(Bengals, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 670, 100, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/bengals_jpg.jpg"))); // NOI18N
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));

        jScrollPane3.setViewportView(jPanel4);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 480, 540));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setBackground(new java.awt.Color(0, 0, 0));
        Exit.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/icons8_close_window_30px.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 13, 33, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/logo-2 30px.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/cat_footprint_kecil.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 13, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/cat_footprint_kecil.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 47));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/cat_footprint_gede.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/cat_footprint_24px.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 25, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/cat_footprint_24px.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 19, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 50));

        jPanel3.setBackground(new java.awt.Color(159, 217, 245));
        jPanel3.setForeground(new java.awt.Color(75, 102, 168));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(tanggal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("→");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, -1, 20));
        jPanel3.add(tanggal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, -1, -1));

        namapemilik.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        namapemilik.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        namapemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namapemilikActionPerformed(evt);
            }
        });
        jPanel3.add(namapemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 219, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setText("Tanggal Penitipan");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        jam.setBackground(new java.awt.Color(204, 204, 255));
        jam.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "08.00-10.00", "13.00-14.30", "16.00-18.00" }));
        jam.setToolTipText("");
        jam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamActionPerformed(evt);
            }
        });
        jam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jamKeyPressed(evt);
            }
        });
        jPanel3.add(jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 210, 30));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setText("Jam Pengambilan");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, 20));

        sehari.setBackground(new java.awt.Color(159, 217, 245));
        lamapenitipan.add(sehari);
        sehari.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        sehari.setText("1 Hari ");
        sehari.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sehari.setBorderPainted(true);
        sehari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sehariMouseClicked(evt);
            }
        });
        sehari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sehariActionPerformed(evt);
            }
        });
        jPanel3.add(sehari, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        lebihsehari.setBackground(new java.awt.Color(159, 217, 245));
        lamapenitipan.add(lebihsehari);
        lebihsehari.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lebihsehari.setText("Lebih dari 1 Hari ");
        lebihsehari.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lebihsehari.setBorderPainted(true);
        lebihsehari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lebihsehariMouseClicked(evt);
            }
        });
        lebihsehari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lebihsehariActionPerformed(evt);
            }
        });
        jPanel3.add(lebihsehari, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, -1, -1));

        berat.setBackground(new java.awt.Color(204, 204, 255));
        berat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        berat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "1-3 Kg", "4-6 Kg", "7-9 Kg", ">10 Kg" }));
        berat.setToolTipText("");
        berat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                beratItemStateChanged(evt);
            }
        });
        berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratActionPerformed(evt);
            }
        });
        jPanel3.add(berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 220, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Lama Penitipan");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Berat Kucing");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Jenis Kucing");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        kucingan.setBackground(new java.awt.Color(204, 204, 255));
        kucingan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kucingan.setText("Pilih");
        kucingan.setBorder(null);
        kucingan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        kucingan.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        kucingan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kucinganActionPerformed(evt);
            }
        });
        jPanel3.add(kucingan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 60, 30));

        add.setBackground(new java.awt.Color(51, 255, 51));
        add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/icons8_cat_footprint_30px_1.png"))); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel3.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, -1, -1));

        batal.setBackground(new java.awt.Color(255, 0, 51));
        batal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/icons8_cat_footprint_30px_1.png"))); // NOI18N
        batal.setToolTipText("");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel3.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Nama Pemilik");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        target.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        target.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        target.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetActionPerformed(evt);
            }
        });
        jPanel3.add(target, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 140, 30));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel14.setText("Daftar");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel21.setText("Clear");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/samping.png"))); // NOI18N
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/image/lari samping.png"))); // NOI18N
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 890, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namapemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapemilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapemilikActionPerformed
 
    private void daftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarMouseClicked
        // TODO add your handling code here:
        int index = daftar.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)daftar.getModel();
        String Nama = model.getValueAt(index, 0).toString();
        setget.setNama(Nama);
        String Jenis = model.getValueAt(index, 1).toString();
        setget.setJenis(Jenis);
        String Berat = model.getValueAt(index, 2).toString();
        setget.setBerat(Berat);
        String LamaPenitipan = model.getValueAt(index, 3).toString();
        setget.setLamaPenitipan(LamaPenitipan);
        String Tanggal1 = model.getValueAt(index, 4).toString();
        setget.setTanggal1(Tanggal1);
        String Tanggal2 = model.getValueAt(index, 5).toString();
        setget.setTanggal2(Tanggal2);
        String Jam = model.getValueAt(index, 6).toString();
        setget.setJam(Jam);
        
       
        detail.setVisible(true);
        detail.pack();
        detail.setLocationRelativeTo(null);
        detail.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        detail.Nama.setText(setget.getNama());
        detail.Berat.setText(setget.getBerat());
        detail.Jam.setText(setget.getJam());
        detail.Tanggal1.setText(setget.getTanggal1());
        detail.Tanggal2.setText(setget.getTanggal2());
        detail.Jenis.setText(setget.getJenis());
        detail.Lama.setText(setget.getLamaPenitipan());
    }//GEN-LAST:event_daftarMouseClicked

    private void sehariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sehariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sehariActionPerformed

    private void lebihsehariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lebihsehariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lebihsehariActionPerformed

    private void jamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        namapemilik.setText(namapemilik.getText());
        setget.setNama(namapemilik.getText());
        String Berat = berat.getSelectedItem().toString();
        setget.setBerat(Berat);
        String Tanggal1 = ((JTextField)tanggal1.getDateEditor().getUiComponent()).getText();
        setget.setTanggal1(Tanggal1);
        String Tanggal2 = ((JTextField)tanggal2.getDateEditor().getUiComponent()).getText();
        setget.setTanggal2(Tanggal2);
        String LamaPenitipan = lamapenitipan.getSelection().getActionCommand();
        setget.setLamaPenitipan(LamaPenitipan);
        String Jenis = jeniskucing.getSelection().getActionCommand();
        setget.setJenis(Jenis);
        String Jam = jam.getSelectedItem().toString();
        setget.setJam(Jam);
        if (namapemilik.getText().trim().isEmpty() || "Pilih...".equals(Berat) || "Pilih...".equals(Jam) || Tanggal2.trim().isEmpty() && Tanggal1.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "ISI DENGAN LENGKAP", "WARNING", HEIGHT);
        }
        else {
            JOptionPane.showMessageDialog(null, "data berhasil ditambahkan", "SUCCESSFULLY", HEIGHT);
            DefaultTableModel model = (DefaultTableModel) daftar.getModel();
            model.addRow(new Object[]{setget.getNama(), setget.getJenis(), setget.getBerat(), setget.getLamaPenitipan(), setget.getTanggal1(), setget.getTanggal2(), setget.getJam()});
        }
    }//GEN-LAST:event_addActionPerformed

    private void beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beratActionPerformed

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMousePressed

    int xx, xy;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void kucinganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kucinganActionPerformed
        jScrollPane3.setVisible(true);
        jScrollPane1.setVisible(false);
        jScrollPane3.getViewport().setViewPosition(new Point(0,0));
    }//GEN-LAST:event_kucinganActionPerformed

    private void beratItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_beratItemStateChanged
        // TODO add your handling code here:
        if(berat.getSelectedItem().equals("1")){
        }
        else if (berat.getSelectedItem().equals("2")){
        }
        else if (berat.getSelectedItem().equals("3")){
        }
        else if (berat.getSelectedItem().equals("4")){
        }
    }//GEN-LAST:event_beratItemStateChanged

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        namapemilik.setText("");
        tanggal1.setDate(null);
        tanggal2.setDate(null);
        berat.setSelectedItem("Pilih");
        jam.setSelectedItem("Pilih");
        sehari.setSelected(true);
        target.setText("");
        Siamese.setSelected(true);
        tanggal2.setEnabled(false);
        
    }//GEN-LAST:event_batalActionPerformed

    private void targetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetActionPerformed

    private void jamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jamKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamKeyPressed

    private void SiameseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiameseActionPerformed
        // TODO add your handling code here:
        target.setText("Siamese");
    }//GEN-LAST:event_SiameseActionPerformed

    private void BritishshorthairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BritishshorthairActionPerformed
        // TODO add your handling code here:
        target.setText("British Shorthair");
    }//GEN-LAST:event_BritishshorthairActionPerformed

    private void PersiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersiansActionPerformed
        // TODO add your handling code here:
        target.setText("Persians");
    }//GEN-LAST:event_PersiansActionPerformed

    private void RagdollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RagdollActionPerformed
        // TODO add your handling code here:
        target.setText("Ragdoll");
    }//GEN-LAST:event_RagdollActionPerformed

    private void AnggoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnggoraActionPerformed
        // TODO add your handling code here:
        target.setText("Anggora");
    }//GEN-LAST:event_AnggoraActionPerformed

            
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jScrollPane3.setVisible(false);
        jScrollPane1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lebihsehariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lebihsehariMouseClicked
        // TODO add your handling code here:
        tanggal2.setEnabled(true);
    }//GEN-LAST:event_lebihsehariMouseClicked

    private void sehariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sehariMouseClicked
        // TODO add your handling code here:
        tanggal2.setEnabled(false);
    }//GEN-LAST:event_sehariMouseClicked
    private void DomestikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomestikActionPerformed
        // TODO add your handling code here:
        target.setText("Domestik");
    }//GEN-LAST:event_DomestikActionPerformed

    private void BengalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BengalsActionPerformed
        // TODO add your handling code here:
        target.setText("Bengals");
    }//GEN-LAST:event_BengalsActionPerformed

    private void SphynxesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SphynxesActionPerformed
        // TODO add your handling code here:
        target.setText("Sphynxes");
    }//GEN-LAST:event_SphynxesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarKucing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarKucing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarKucing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarKucing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DaftarKucing().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Anggora;
    private javax.swing.JRadioButton Bengals;
    private javax.swing.JRadioButton Britishshorthair;
    private javax.swing.JRadioButton Domestik;
    private javax.swing.JLabel Exit;
    private javax.swing.JRadioButton Persians;
    private javax.swing.JRadioButton Ragdoll;
    private javax.swing.JRadioButton Siamese;
    private javax.swing.JRadioButton Sphynxes;
    private javax.swing.JButton add;
    private javax.swing.JButton batal;
    private javax.swing.JComboBox<String> berat;
    public javax.swing.JTable daftar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jam;
    private javax.swing.ButtonGroup jeniskucing;
    private javax.swing.JButton kucingan;
    private javax.swing.ButtonGroup lamapenitipan;
    private javax.swing.JRadioButton lebihsehari;
    private javax.swing.JTextField namapemilik;
    private javax.swing.JRadioButton sehari;
    private org.netbeans.modules.form.InvalidComponent tanggal1;
    private org.netbeans.modules.form.InvalidComponent tanggal2;
    private javax.swing.JTextField target;
    // End of variables declaration//GEN-END:variables
}
